# Map each genus to Uniprot Proteome ID

## Configuration

In [1]:
import pandas as pd
import os
import json
import requests
import pickle
from difflib import SequenceMatcher

In [28]:
filt_d = "./data/FILTERED_S.xlsx"
genus_f = "./data/Students_Samples_abundance_FILTERED.csv"

human_brain = "./data/gut_c3/Human_proteins_brain_f.csv"
human_gut = "./data/gut_c3/Human_proteins_gut_f.csv"

## Find Proteome IDs mapped from clinical data
* **by hand**

* **from hgma**

In [3]:
# Read filt_d: only need the first two sheets (hand_mapped and hgma)
filt_df_1 = pd.read_excel(filt_d, index_col=None, header=None, sheet_name="hand_mapped")
# Add column names
filt_df_1.columns = ["Genus", "Proteome ID"]

filt_df_2 = pd.read_excel(filt_d, index_col=None, header=0, sheet_name="hgma")
# Only keep name and proteome ID columns
filt_df_2 = filt_df_2[["name", "Proteome ID(with higher BUSCO)"]]
filt_df_2.columns = ["Species", "Proteome ID"]

In [4]:
filt_df_1

                               Genus  Proteome ID
0                   g__Alloscardovia  UP000016519
1                 g__Arcanobacterium  UP000293036
2                  g__Brevibacterium  UP000031488
3                         g__CAG-352  UP000018340
4   g__Christensenellaceae R-7 group  UP000531233
..                               ...          ...
58     g__unknown_ Saccharimonadales  UP000013893
59        g__unknown_ Synergistaceae  UP000259231
60       g__unknown_ Veillonellaceae  UP000070542
61        g__unknown_ Victivallaceae  UP000245959
62                 g__unknown_ W5053  UP000016618

[63 rows x 2 columns]

In [5]:
filt_df_2

                                               Species  Proteome ID
0                           Acidaminococcus fermentans  UP000182379
1                            Acidaminococcus intestini  UP000754226
2                          Acidaminococcus sp. CAG:542  UP000018195
3                                     Actinomyces oris  UP000185603
4                          Adlercreutzia equolifaciens  UP000472380
..                                                 ...          ...
410                                Peptoniphilus harei  UP000250070
411                           Peptoniphilus lacrimalis  UP000255517
412                        unclassified Prevotellaceae  UP000182805
413                      unclassified Rhodospirillales  UP000438537
414  [Ruminococcaceae] bacterium D16 / Clostridiale...  UP000002801

[415 rows x 2 columns]

## Create taxonomy list for study

In [6]:
# Read genus_f
genus_df = pd.read_csv(genus_f, index_col=0)

# Taxonomy list from column name
tax_list = list(genus_df["Taxonomy"])
tax_list

['g__Acidaminococcus',
 'g__Actinomyces',
 'g__Adlercreutzia',
 'g__Aeromonas',
 'g__Akkermansia',
 'g__Alistipes',
 'g__Allisonella',
 'g__Alloprevotella',
 'g__Alloscardovia',
 'g__AM778010_g',
 'g__Anaeroplasma',
 'g__Anaerostipes',
 'g__Anaerotruncus',
 'g__Arcanobacterium',
 'g__Asteroleplasma',
 'g__Atopobium',
 'g__Bacteroides',
 'g__Bacteroides pectinophilus group',
 'g__Barnesiella',
 'g__Bifidobacterium',
 'g__Bilophila',
 'g__Blautia',
 'g__Brevibacterium',
 'g__Butyricicoccus',
 'g__Butyricimonas',
 'g__Butyrivibrio',
 'g__CAG-352',
 'g__Campylobacter',
 'g__Catenibacterium',
 'g__Christensenellaceae R-7 group',
 'g__Cloacibacillus',
 'g__Clostridium innocuum group',
 'g__Clostridium sensu stricto 1',
 'g__Clostridium sensu stricto 13',
 'g__Clostridium sensu stricto 2',
 'g__Colidextribacter',
 'g__Collinsella',
 'g__Comamonas',
 'g__Coprobacillus',
 'g__Coprobacter',
 'g__Coprococcus',
 'g__Corynebacterium',
 'g__Cutibacterium',
 'g__Dermabacter',
 'g__Desulfovibrio',
 'g__Dialister',
 'g__Dorea',
 'g__DTU089',
 'g__Eggerthella',
 'g__Eikenella',
 'g__Elusimicrobium',
 'g__Enterococcus',
 'g__Epulopiscium',
 'g__Erysipelatoclostridium',
 'g__Erysipelotrichaceae UCG-003',
 'g__Escherichia-Shigella',
 'g__EU469726_g',
 'g__Eubacterium',
 'g__Eubacterium eligens group',
 'g__Eubacterium hallii group',
 'g__Eubacterium nodatum group',
 'g__Eubacterium siraeum group',
 'g__Eubacterium ventriosum group',
 'g__Facklamia',
 'g__Faecalibacterium',
 'g__Faecalitalea',
 'g__Family XIII AD3011 group',
 'g__Filifactor',
 'g__Flavonifractor',
 'g__Frisingicoccus',
 'g__Fusicatenibacter',
 'g__Fusobacterium',
 'g__Gardnerella',
 'g__GCA-900066575',
 'g__Gemella',
 'g__Globicatella',
 'g__Granulicatella',
 'g__Haemophilus',
 'g__Hafnia-Obesumbacterium',
 'g__Helicobacter',
 'g__Holdemanella',
 'g__Incertae Sedis',
 'g__JN713383_g',
 'g__Klebsiella',
 'g__Lachnoanaerobaculum',
 'g__Lachnoclostridium',
 'g__Lachnospiraceae FE2018 group',
 'g__Lachnospiraceae ND3007 group',
 'g__Lachnospiraceae NK3A20 group',
 'g__Lachnospiraceae NK4A136 group',
 'g__Lachnospiraceae UCG-003',
 'g__Lactobacillus',
 'g__Lactococcus',
 'g__Lawsonella',
 'g__Lentimicrobium',
 'g__Leuconostoc',
 'g__Megamonas',
 'g__Megasphaera',
 'g__Methanobrevibacter',
 'g__Mitsuokella',
 'g__Mobiluncus',
 'g__Monoglobus',
 'g__Negativibacillus',
 'g__Negativicoccus',
 'g__NK4A214 group',
 'g__Odoribacter',
 'g__Oribacterium',
 'g__Oscillibacter',
 'g__Oscillospira',
 'g__PAC000683_g',
 'g__Paludicola',
 'g__Parabacteroides',
 'g__Paraprevotella',
 'g__Parasutterella',
 'g__Pedobacter',
 'g__Peptoclostridium',
 'g__Peptococcus',
 'g__Peptostreptococcus',
 'g__Phascolarctobacterium',
 'g__Porphyromonas',
 'g__Prevotella',
 'g__Prevotellaceae NK3B31 group',
 'g__Prevotellaceae UCG-001',
 'g__Prevotellaceae UCG-003',
 'g__Proteus',
 'g__Pyramidobacter',
 'g__Rikenellaceae RC9 gut group',
 'g__Roseburia',
 'g__Ruminococcus',
 'g__Ruminococcus torques group',
 'g__Ruminococcus_g2',
 'g__S5-A14a',
 'g__Selenomonas',
 'g__Sellimonas',
 'g__Senegalimassilia',
 'g__Slackia',
 'g__Sneathia',
 'g__Solobacterium',
 'g__Staphylococcus',
 'g__Streptococcus',
 'g__Subdoligranulum',
 'g__Succinivibrio',
 'g__Sutterella',
 'g__Treponema',
 'g__Turicibacter',
 'g__Tyzzerella',
 'g__UBA1819',
 'g__UCG-002',
 'g__UCG-003',
 'g__UCG-004',
 'g__UCG-005',
 'g__UCG-009',
 'g__unknown_ Actinomycetaceae',
 'g__unknown_ Anaerococcus',
 'g__unknown_ Anaerovoracaceae',
 'g__unknown_ Atopobiaceae',
 'g__unknown_ Bacteroidales',
 'g__unknown_ Barnesiellaceae',
 'g__unknown_ Burkholderiales',
 'g__unknown_ Butyricicoccaceae',
 'g__unknown_ Chloroplast',
 'g__unknown_ Christensenellaceae',
 'g__unknown_ Clostridia UCG-014',
 'g__unknown_ Clostridia vadinBB60 group',
 'g__unknown_ Coriobacteriales Incertae Sedis',
 'g__unknown_ Eggerthellaceae',
 'g__unknown_ Erysipelotrichaceae',
 'g__unknown_ Eubacterium coprostanoligenes group',
 'g__unknown_ Ezakiella',
 'g__unknown_ Fastidiosipila',
 'g__unknown_ Fenollaria',
 'g__unknown_ Finegoldia',
 'g__unknown_ Gallicola',
 'g__unknown_ Gastranaerophilales',
 'g__unknown_ Helcococcus',
 'g__unknown_ Hydrogenoanaerobacterium',
 'g__unknown_ Izemoplasmatales',
 'g__unknown_ Lachnospiraceae',
 'g__unknown_ Marinifilaceae',
 'g__unknown_ Micrococcaceae',
 'g__unknown_ Murdochiella',
 'g__unknown_ Muribaculaceae',
 'g__unknown_ Oscillospiraceae',
 'g__unknown_ Parvimonas',
 'g__unknown_ Peptococcaceae',
 'g__unknown_ Peptoniphilus',
 'g__unknown_ Peptostreptococcaceae',
 'g__unknown_ Peptostreptococcales-Tissierellales',
 'g__unknown_ Prevotellaceae',
 'g__unknown_ Puniceicoccaceae',
 'g__unknown_ RF39',
 'g__unknown_ Rhodospirillales',
 'g__unknown_ Ruminococcaceae',
 'g__unknown_ Saccharimonadales',
 'g__unknown_ Synergistaceae',
 'g__unknown_ UCG-010',
 'g__unknown_ Veillonellaceae',
 'g__unknown_ Victivallaceae',
 'g__unknown_ W5053',
 'g__unknown_ WCHB1-41',
 'g__Varibaculum',
 'g__Veillonella',
 'g__Victivallis',
 'g__Weissella']

## Map Species names from hgma to Taxonomy

In [7]:
# For every entry of filt_df_2, compare simillarity of species name with genus name from tax_list

# Remove g__ (3 characters) from tax_list
tax_list_n = []
for i in range(len(tax_list)):
    tax_list_n.append(tax_list[i][3:])
match_genus_l = []
for i in range(len(filt_df_2)):
    score_list = []
    for j in range(len(tax_list_n)):
            # Calculate sequence similarity score
            score = SequenceMatcher(None, filt_df_2["Species"][i], tax_list_n[j]).ratio()
            # Append to score_list with scores for every entry
            score_list.append(score)
    # Find index of highest score
    index = score_list.index(max(score_list))
    # Find genus of highest score
    match_genus = tax_list[index]
    # Append to match_genus_l
    match_genus_l.append(match_genus)
    print(filt_df_2["Species"][i], "/", match_genus)
# Add match_genus_l to filt_df_2
filt_df_2["Genus"] = match_genus_l
# Drop species column
filt_df_2 = filt_df_2.drop(columns=["Species"])

Acidaminococcus fermentans / g__Acidaminococcus
Acidaminococcus intestini / g__Acidaminococcus
Acidaminococcus sp. CAG:542 / g__Acidaminococcus
Actinomyces oris / g__Actinomyces
Adlercreutzia equolifaciens / g__Adlercreutzia
Aeromonas caviae / g__Aeromonas
Aeromonas veronii / g__Aeromonas
Akkermansia muciniphila / g__Akkermansia
Akkermansia sp. KLE1605 / g__Akkermansia
unclassified Akkermansia / g__Akkermansia
unclassified Akkermansiaceae / g__Akkermansia
Alistipes finegoldii / g__Alistipes
Alistipes indistinctus / g__Alistipes
Alistipes obesi / g__Alistipes
Alistipes onderdonkii / g__Alistipes
Alistipes putredinis / g__Alistipes
Alistipes shahii / g__Alistipes
Alistipes sp. An31A  / g__Alistipes
Alistipes sp. CAG:268 / g__Alistipes
Alistipes sp. CHKCI003 / g__Alistipes
Alistipes timonensis / g__Alistipes
unclassified Alistipes / g__Alistipes
Allisonella histaminiformans / g__Allisonella
Alloprevotella tannerae / g__Alloprevotella
unclassified_Anaeroplasmataceae / g__Anaeroplasma
Anaerostipes caccae / g__Anaerostipes
Anaerostipes hadrus  / g__Anaerostipes
[Anaerotruncus] sp. CAG:390 / g__Anaerotruncus
Anaerotruncus colihominis / g__Anaerotruncus
Anaerotruncus sp. CAG:528 / g__Anaerotruncus
Atopobium parvulum / g__Atopobium
[Bacteroides] sp. 43_108 / g__Bacteroides
[Bacteroides] sp. CAG:144 / g__Bacteroides
[Bacteroides] sp. CAG:545 / g__Bacteroides
[Bacteroides] sp. CAG:709 / g__Bacteroides
[Bacteroides] sp. CAG:770 / g__Bacteroides
[Bacteroides] sp. CAG:927 / g__Bacteroides
Bacteroides acidifaciens / g__Bacteroides
Bacteroides barnesiae / g__Bacteroides
Bacteroides caccae / g__Bacteroides
Bacteroides cellulosilyticus / g__Bacteroides pectinophilus group
Bacteroides clarus / g__Bacteroides
Bacteroides coprocola / g__Bacteroides
Bacteroides coprophilus / g__Bacteroides pectinophilus group
Bacteroides dorei / g__Bacteroides
Bacteroides eggerthii / g__Bacteroides
Bacteroides faecichinchillae / g__Bacteroides pectinophilus group
Bacteroides faecis / g__Bacteroides
Bacteroides finegoldii / g__Bacteroides
Bacteroides fluxus / g__Bacteroides
Bacteroides fragilis 1 / g__Bacteroides
Bacteroides intestinalis / g__Bacteroides pectinophilus group
Bacteroides massiliensis / g__Bacteroides
Bacteroides nordii / g__Bacteroides
Bacteroides oleiciplenus / g__Bacteroides
Bacteroides ovatus / g__Bacteroides
Bacteroides plebeius / g__Bacteroides
Bacteroides salanitronis / g__Bacteroides
Bacteroides salyersiae / g__Bacteroides
Bacteroides sartorii / g__Bacteroides
Bacteroides sp. An19  / g__Bacteroides
Bacteroides sp. An269 / g__Bacteroides
Bacteroides sp. An279 / g__Bacteroides
Bacteroides sp. An322 / g__Bacteroides
Bacteroides sp. An51A  / g__Bacteroides
Bacteroides sp. CAG:443 / g__Bacteroides
Bacteroides sp. CAG:462 / g__Bacteroides
Bacteroides sp. CAG:530 / g__Bacteroides
Bacteroides stercorirosoris / g__Bacteroides
Bacteroides stercoris / g__Bacteroides
Bacteroides thetaiotaomicron / g__Bacteroides pectinophilus group
Bacteroides uniformis / g__Bacteroides
Bacteroides vulgatus / g__Bacteroides
Bacteroides xylanisolvens / g__Bacteroides
[Bacteroides] coagulans / g__Bacteroides
[Bacteroides] pectinophilus / g__Bacteroides pectinophilus group
Barnesiella intestinihominis / g__Barnesiella
Barnesiella sp. An22 / g__Barnesiella
unclassified Barnesiellaceae / g__unknown_ Barnesiellaceae
Bifidobacterium adolescentis / g__Bifidobacterium
Bifidobacterium angulatum / g__Bifidobacterium
Bifidobacterium animalis / g__Bifidobacterium
Bifidobacterium bifidum / g__Bifidobacterium
Bifidobacterium breve / g__Bifidobacterium
Bifidobacterium catenulatum / g__Bifidobacterium
Bifidobacterium dentium / g__Bifidobacterium
Bifidobacterium gallinarum == saeculare / g__Bifidobacterium
Bifidobacterium longum / g__Bifidobacterium
Bifidobacterium pseudocatenulatum / g__Bifidobacterium
Bifidobacterium scardovii / g__Bifidobacterium
Bifidobacterium thermacidophilum / g__Bifidobacterium
Bilophila wadsworthia / g__Bilophila
unclassified Bilophila / g__Bilophila
[Ruminococcus] sp. CAG:17 / Blautia sp. 2789STDY5608880 / g__Ruminococcus_g2
Blautia coccoides == Blautia producta / g__Bacteroides pectinophilus group
Blautia hansenii / g__Blautia
Blautia hydrogenotrophica / g__unknown_ Hydrogenoanaerobacterium
Blautia massiliensis / g__Blautia
Blautia obeum / g__Blautia
Blautia producta 2 / g__Blautia
Blautia sp. CAG:257 / g__Blautia
Blautia sp. CAG:52 & SG-772 & sp. 2789STDY5834917 / g__Blautia
Blautia sp. N6H1-15 / g__Blautia
Blautia wexlerae / g__Blautia
[Butyricicoccus] pullicaecorum / g__Butyricicoccus
Butyricimonas virosa / g__Butyricimonas
unclassified Butyricimonas / g__Butyricimonas
Butyrivibrio crossotus / g__Butyrivibrio
Butyrivibrio sp. CAG:318 / g__Butyrivibrio
Campylobacter concisus 2 / g__Campylobacter
Campylobacter hominis / g__Campylobacter
Catenibacterium mitsuokai / g__Catenibacterium
Catenibacterium sp. CAG:290 / g__Catenibacterium
Cloacibacillus evryensis / g__Cloacibacillus
Cloacibacillus porcorum / g__Cloacibacillus
Collinsella aerofaciens / g__Collinsella
Collinsella intestinalis / g__Collinsella
Collinsella stercoris / g__Collinsella
Collinsella tanakaei / g__Collinsella
unclassified Collinsella / g__Collinsella
Comamonas kerstersii / g__Comamonas
[Coprobacillus] sp. CAG:605 / g__Coprobacillus
[Coprobacillus] sp. CAG:698 / g__Coprobacillus
[Coprobacillus] sp. CAG:826 / g__Coprobacillus
Coprobacillus cateniformis / g__Coprobacillus
Coprobacter fastidiosus / g__Coprobacter
Coprobacter secundus  / g__Coprobacter
unclassified Coprobacter / g__Coprobacter
Coprococcus catus / g__Coprococcus
Coprococcus comes / g__Coprococcus
Coprococcus eutactus 1 / g__Coprococcus
Coprococcus eutactus 2 / g__Coprococcus
Coprococcus sp. CAG:782 / g__Coprococcus
Desulfovibrio desulfuricans / g__Desulfovibrio
Desulfovibrio desulfuricans 2 / g__Desulfovibrio
Desulfovibrio fairfieldensis / g__Desulfovibrio
Desulfovibrio piger / g__Desulfovibrio
Desulfovibrio sp. An276 / g__Desulfovibrio
Desulfovibrionaceae bacterium CIM:MAG 900 / g__Desulfovibrio
unclassified Desulfovibrio / g__Desulfovibrio
uncultured Desulfovibrio sp. RUG514 / g__Desulfovibrio
Eggerthella lenta / g__Eggerthella
Eggerthella sinensis / g__Eggerthella
Eggerthella sp. 51_9 & CAG:209 / g__Eggerthella
Eggerthella sp. CAG:1427 / g__Eggerthella
Eggerthella sp. CAG:298 / g__Eggerthella
Eggerthella sp. CAG:368 / g__Eggerthella
unclassified Eggerthella / g__Eggerthella
unclassified Eggerthellaceae / g__unknown_ Eggerthellaceae
Enterococcus asini / g__Enterococcus
Enterococcus avium / g__Enterococcus
Enterococcus faecalis / g__Enterococcus
Enterococcus faecium / g__Enterococcus
Enterococcus gallinarum / g__Enterococcus
Erysipelatoclostridium ramosum / g__Erysipelatoclostridium
Erysipelatoclostridium sp1 / g__Erysipelatoclostridium
Erysipelatoclostridium sp2 / g__Erysipelatoclostridium
Erysipelotrichaceae bacterium 3_1_53 / g__Erysipelotrichaceae UCG-003
Erysipelotrichaceae bacterium 5_2_54FAA / [Eubacterium] sp. 3_1_31 / g__Erysipelotrichaceae UCG-003
unclassified_Erysipelotrichaceae / g__unknown_ Erysipelotrichaceae
Escherichia coli / g__Escherichia-Shigella
Escherichia fergusonii / g__Escherichia-Shigella
[Eubacteriaceae] bacterium CHKCI004 & [Eubacterium] sp. An3 / g__Catenibacterium
[Eubacterium] eligens / g__Eubacterium eligens group
[Eubacterium] ramulus / g__Eubacterium siraeum group
[Eubacterium] rectale / g__Eubacterium
[Eubacterium] siraeum / g__Eubacterium siraeum group
[Eubacterium] sp. 36_13 & CAG:86 & RUG185 / g__Eubacterium eligens group
[Eubacterium] sp. 38_16 & CAG:146 / g__Eubacterium
[Eubacterium] sp. CAG:115 / g__Eubacterium
[Eubacterium] sp. CAG:156 / g__Eubacterium
[Eubacterium] sp. CAG:161 / g__Eubacterium
[Eubacterium] sp. CAG:180 / g__Eubacterium
[Eubacterium] sp. CAG:248 / g__Eubacterium
[Eubacterium] sp. CAG:251 / [Clostridium] sp. A254.MGS-251 / g__Eubacterium ventriosum group
[Eubacterium] sp. CAG:274 / g__Eubacterium
[Eubacterium] sp. CAG:38 / g__Eubacterium
[Eubacterium] sp. CAG:581 / g__Eubacterium
[Eubacterium] sp. CAG:603 & sp. 2789STDY5608818 / g__Eubacterium eligens group
[Eubacterium] sp. CAG:841 / g__Eubacterium
[Eubacterium] ventriosum / g__Eubacterium ventriosum group
[Eubacterium] sp. Marseille-P5640 / g__Eubacterium hallii group
Erysipelotrichaceae bacterium 5_2_54FAA / [Eubacterium] sp. 3_1_31 / g__Erysipelotrichaceae UCG-003
[Faecalibacterium] sp. CAG:1138 / g__Faecalibacterium
[Faecalibacterium] sp. CAG:74 / g__Faecalibacterium
Faecalibacterium prausnitzii  / g__Faecalibacterium
Faecalitalea cylindroides / g__Faecalitalea
Flavonifractor plautii / g__Flavonifractor
Flavonifractor sp. 2789STDY5834931 / Clostridiales bacterium CCNA10 / g__Flavonifractor
Flavonifractor sp. An10 / g__Flavonifractor
Fusicatenibacter saccharivorans / g__Fusicatenibacter
[Fusobacterium] sp. CAG:439 / g__Fusobacterium
Fusobacterium gonidiaformans / g__Fusobacterium
Fusobacterium mortiferum / g__Fusobacterium
Fusobacterium necrophorum / g__Fusobacterium
Fusobacterium nucleatum subsp. animalis / g__Eubacterium nodatum group
Fusobacterium nucleatum subsp. polymorphum / g__Eubacterium nodatum group
Fusobacterium periodonticum / g__Fusobacterium
Fusobacterium sp. clos_1_1 / g__Fusobacterium
Fusobacterium ulcerans / g__Fusobacterium
Fusobacterium varium / g__Fusobacterium
unclassified Fusobacterium / g__Bifidobacterium
unclassified Fusobacterium / g__Bifidobacterium
Gemella sanguinis / g__Gemella
Granulicatella adiacens / g__Granulicatella
Haemophilus parahaemolyticus / g__Haemophilus
Haemophilus parainfluenzae / g__Haemophilus
Haemophilus paraphrohaemolyticus / g__Haemophilus
Haemophilus pittmaniae / g__Haemophilus
Haemophilus quentini / g__Haemophilus
Haemophilus sputorum / g__Haemophilus
Hafnia paralvei / g__Hafnia-Obesumbacterium
Helicobacter winghamensis / g__Helicobacter
Holdemanella biformis / g__Holdemanella
unclassified_Holdemanella / g__Holdemanella
unclassified Lentisphaerae / g__Megasphaera
unclassified Proteobacteria / g__Bifidobacterium
Klebsiella aerogenes / g__Klebsiella
Klebsiella michiganensis 1 / g__Klebsiella
Klebsiella michiganensis 2 / g__Klebsiella
Klebsiella oxytoca / g__Klebsiella
Klebsiella pneumoniae / g__Klebsiella
Klebsiella quasipneumoniae / g__Klebsiella
Klebsiella variicola / g__Klebsiella
Lachnoanaerobaculum saburreum  / g__Lachnoanaerobaculum
Lachnoclostridium phytofermentans 2 / g__Lachnoclostridium
Lachnoclostridium sp. An118 / g__Lachnoclostridium
Lachnoclostridium sp. An138 / g__Lachnoclostridium
Lachnoclostridium sp. An14 / g__Lachnoclostridium
Lachnoclostridium sp. SNUG30386 / [Clostridium] sp. CAG:43 / g__Lachnoclostridium
Lachnospiraceae bacterium CIM:MAG 844 / Firmicutes bacterium CAG:95 / g__Lachnospiraceae UCG-003
Lachnospiraceae bacterium hRUG904 / Clostridiales bacterium RUG495 / [Clostridium] sp. CAG:127 / g__Eubacterium siraeum group
Roseburia sp. CAG:100 / Lachnospiraceae bacterium CIM:MAG 54 / g__Lachnospiraceae UCG-003
Lactobacillus acidophilus / g__Lactobacillus
Lactobacillus amylovorus / g__Lactobacillus
Lactobacillus casei == paracasei / g__Lactobacillus
Lactobacillus crispatus / g__Lactobacillus
Lactobacillus delbrueckii / g__Lactobacillus
Lactobacillus fermentum / g__Lactobacillus
Lactobacillus gallinarum / g__Lactobacillus
Lactobacillus gasseri / g__Lactobacillus
Lactobacillus johnsonii / g__Lactobacillus
Lactobacillus mucosae / g__Lactobacillus
Lactobacillus oris / g__Lactobacillus
Lactobacillus parabuchneri / g__Lactobacillus
Lactobacillus paragasseri / g__Lactobacillus
Lactobacillus reuteri / g__Lactobacillus
Lactobacillus ruminis / g__Lactobacillus
Lactobacillus salivarius / g__Lactobacillus
Lactobacillus vaginalis / g__Lactobacillus
Lactococcus lactis subsp. cremoris / g__Lactococcus
Lactococcus lactis subsp. lactis / g__Lactococcus
Leuconostoc mesenteroides / g__Leuconostoc
Megamonas funiformis == rupellensis / g__Megamonas
Caecibacter massiliensis == Megasphaera hexanoica / g__Eubacterium eligens group
Megasphaera elsdenii / g__Megasphaera
Megasphaera micronuciformis / g__Megasphaera
Megasphaera sp. ASD88 & An286 & AJH120 / g__Megasphaera
Megasphaera sp. BL7 & NM10 / g__Megasphaera
Methanobrevibacter smithii 1 / g__Methanobrevibacter
Methanobrevibacter smithii 2 / g__Methanobrevibacter
Mitsuokella jalaludinii / g__Mitsuokella
Mitsuokella multacida / g__Mitsuokella
Monoglobus pectinilyticus / g__Monoglobus
Odoribacter laneus / g__Odoribacter
Odoribacter splanchnicus / g__Odoribacter
Oribacterium sinus / g__Oribacterium
Oscillibacter sp. CAG:155 / g__Oscillibacter
Oscillibacter sp. CAG:241 & CIM:MAG 164_1 / g__Oscillibacter
Oscillibacter sp. CAG:241_62_21 / g__Oscillibacter
Parabacteroides distasonis / g__Parabacteroides
Parabacteroides goldsteinii / g__Parabacteroides
Parabacteroides gordonii / g__Parabacteroides
Parabacteroides johnsonii / g__Parabacteroides
Parabacteroides merdae / g__Parabacteroides
Parabacteroides sp. 426-9 / g__Parabacteroides
Parabacteroides sp. CAG:409 / g__Parabacteroides
unclassified Parabacteroides / g__Parabacteroides
Paraprevotella clara / g__Paraprevotella
Paraprevotella xylaniphila / g__Paraprevotella
Parasutterella excrementihominis / g__Parasutterella
Peptostreptococcus anaerobius / g__Peptostreptococcus
Peptostreptococcus sp. MV1 / g__Peptostreptococcus
Peptostreptococcus stomatis / g__Peptostreptococcus
Phascolarctobacterium faecium / g__Phascolarctobacterium
Phascolarctobacterium sp. CAG:266 / g__Phascolarctobacterium
Phascolarctobacterium succinatutens / g__Phascolarctobacterium
Porphyromonas asaccharolytica / g__Porphyromonas
Porphyromonas endodontalis / g__Porphyromonas
Porphyromonas somerae / g__Porphyromonas
Porphyromonas sp. HMSC065F10 / g__Porphyromonas
unclassified Porphyromonas / g__Porphyromonas
Prevotella bivia / g__Prevotella
Prevotella buccae / g__Prevotella
Prevotella copri 1 / g__Prevotella
Prevotella corporis / g__Prevotella
Prevotella denticola / g__Prevotella
Prevotella disiens / g__Prevotella
Prevotella intermedia / g__Prevotella
Prevotella jejuni / g__Prevotella
Prevotella melaninogenica / g__Prevotella
Prevotella salivae / g__Prevotella
Prevotella sp. 885 / g__Prevotella
Prevotella sp. CAG:1092 / g__Prevotellaceae UCG-001
Prevotella sp. CAG:1124 / g__Prevotellaceae UCG-001
Prevotella sp. CAG:1185 / g__Prevotellaceae UCG-001
Prevotella sp. CAG:1320 / g__Prevotellaceae UCG-001
Prevotella sp. CAG:386 / g__Prevotellaceae UCG-003
Prevotella sp. CAG:474 / g__Prevotella
Prevotella sp. CAG:520 / g__Prevotellaceae UCG-001
Prevotella sp. CAG:604 / g__Prevotellaceae UCG-001
Prevotella sp. CAG:617 / g__Prevotellaceae UCG-001
Prevotella sp. CAG:732 / g__Prevotellaceae UCG-003
Prevotella sp. CAG:891 / g__Prevotellaceae UCG-001
Prevotella stercorea / g__Prevotella
Prevotella timonensis / g__Prevotella
Prevotella veroralis / g__Prevotella
unclassified Prevotella / g__Prevotella
Prevotellaceae bacterium CIM:MAG 724 / g__Prevotellaceae UCG-001
unclassified Prevotellaceae / g__unknown_ Prevotellaceae
Proteus mirabilis / g__Proteus
Pyramidobacter piscolens / g__Pyramidobacter
[Roseburia] sp. CAG:309 / g__Roseburia
[Roseburia] sp. CAG:380 / g__Roseburia
Roseburia faecis / g__Roseburia
Roseburia hominis / g__Roseburia
Roseburia intestinalis / g__Roseburia
Roseburia inulinivorans / g__Roseburia
Roseburia sp. CAG:100 / Lachnospiraceae bacterium CIM:MAG 54 / g__Lachnospiraceae UCG-003
Roseburia sp. CAG:182 / g__Roseburia
Roseburia sp. CAG:197 / g__Roseburia
Roseburia sp. CAG:303 / g__Roseburia
Roseburia sp. CAG:45 & sp. 2789STDY5608886 / g__Roseburia
[Ruminococcus] faecis / g__Ruminococcus
[Ruminococcus] gnavus / g__Ruminococcus
[Ruminococcus] lactaris / g__Ruminococcus
[Ruminococcus] sp. 2789STDY5608794 & sp. 2789STDY5834890 / Firmicutes bacterium CAG:56 / g__Ruminococcus torques group
[Ruminococcus] sp. CAG:17 / Blautia sp. 2789STDY5608880 / g__Ruminococcus_g2
[Ruminococcus] sp. CAG:382 / g__Ruminococcus_g2
[Ruminococcus] sp. CAG:724 / g__Ruminococcus_g2
[Ruminococcus] torques / g__Ruminococcus torques group
Ruminococcus bicirculans / g__Ruminococcus
Ruminococcus bromii 2 / g__Ruminococcus
Ruminococcus callidus / g__Ruminococcus
Ruminococcus champanellensis / g__Ruminococcus
Ruminococcus sp. A254.MGS-254 & CAG:254 / g__Ruminococcus_g2
Ruminococcus sp. CAG:177 / g__Ruminococcus
Ruminococcus sp. CAG:330 / g__Ruminococcus
Ruminococcus sp. CAG:353 & sp. 2789STDY5834938 / g__Ruminococcus_g2
Ruminococcus sp. CAG:403 / g__Ruminococcus
Ruminococcus sp. CAG:488 / g__Ruminococcus
Ruminococcus sp. CAG:563 / g__Ruminococcus
Ruminococcus sp. CAG:579 / g__Ruminococcus
Ruminococcus sp. CAG:624 & UBA6407 & UBA4697 / g__Ruminococcus_g2
Clostridiales bacterium S5-A14a / g__Corynebacterium
Selenomonas artemidis / g__Selenomonas
Selenomonas bovis / g__Selenomonas
Sellimonas intestinalis == Drancourtella massiliensis / g__Senegalimassilia
Senegalimassilia anaerobia / g__Senegalimassilia
Slackia exigua / g__Slackia
Slackia isoflavoniconvertens / g__Flavonifractor
Slackia piriformis / g__Slackia
Solobacterium moorei / g__Solobacterium
[Staphylococcus] sp. CAG:324 / g__Staphylococcus
Streptococcus anginosus / g__Streptococcus
Streptococcus australis / g__Streptococcus
Streptococcus gordonii / g__Streptococcus
Streptococcus infantarius / g__Streptococcus
Streptococcus infantis  / g__Streptococcus
Streptococcus lutetiensis / g__Streptococcus
Streptococcus mitis / g__Streptococcus
Streptococcus mutans / g__Streptococcus
Streptococcus oralis / g__Streptococcus
Streptococcus parasanguinis / g__Streptococcus
Streptococcus pasteurianus / g__Streptococcus
Streptococcus salivarius / g__Streptococcus
Streptococcus sanguinis / g__Streptococcus
Streptococcus sp. I-P16 / g__Streptococcus
Streptococcus thermophilus / g__Streptococcus
Streptococcus vestibularis / g__Streptococcus
[Subdoligranulum] sp. CAG:314 & CIM:MAG 76 / g__Subdoligranulum
Sutterella parvirubra / g__Sutterella
Sutterella sp. CAG:521 / g__Sutterella
Sutterella sp. UBA1442 / g__Sutterella
Sutterella wadsworthensis 1 / g__Sutterella
Sutterella wadsworthensis 2 / g__Sutterella
unclassified Sutterella / g__Sutterella
Treponema succinifaciens / g__Treponema
Turicibacter sanguinis 1 / g__Turicibacter
Tyzzerella nexilis / g__Tyzzerella
Veillonella atypica / g__Veillonella
Veillonella infantium / g__Veillonella
Veillonella magna / g__Veillonella
Veillonella parvula / g__Veillonella
Veillonella rogosae / g__Veillonella
Veillonella seminalis / g__Veillonella
Veillonella tobetsuensis / g__Veillonella
Victivallis vadensis / g__Victivallis
Weissella cibaria / g__Weissella
Weissella confusa / g__Weissella
unclassified Atopobiaceae / g__unknown_ Atopobiaceae
unclassified Bacteroidales / g__unknown_ Bacteroidales
unclassified Bacteroidales [Alistipes] sp. CAG:831 / g__Bacteroides pectinophilus group
unclassified Barnesiellaceae / g__unknown_ Barnesiellaceae
unclassified Eggerthellaceae / g__unknown_ Eggerthellaceae
unclassified_Erysipelotrichaceae / g__unknown_ Erysipelotrichaceae
Candidatus Gastranaerophilales bacterium x14 / g__unknown_ Gastranaerophilales
unclassified Muribaculaceae / g__unknown_ Muribaculaceae
Parvimonas micra / g__unknown_ Parvimonas
Parvimonas sp. KA00067 / g__unknown_ Parvimonas
Peptoniphilus harei / g__unknown_ Peptoniphilus
Peptoniphilus lacrimalis / g__unknown_ Peptoniphilus
unclassified Prevotellaceae / g__unknown_ Prevotellaceae
unclassified Rhodospirillales / g__unknown_ Rhodospirillales
[Ruminococcaceae] bacterium D16 / Clostridiales bacterium Choco116 / g__unknown_ Eubacterium coprostanoligenes group

## Merge filt_df_1 and filt_df_2 : Final match of Genus to Proteome ID

In [8]:
# Concatenate filt_df_1 and filt_df_2
filt_df = pd.concat([filt_df_1, filt_df_2], axis=0)
# Drop duplicates
filt_df = filt_df.drop_duplicates()
filt_df

                                               Genus  Proteome ID
0                                   g__Alloscardovia  UP000016519
1                                 g__Arcanobacterium  UP000293036
2                                  g__Brevibacterium  UP000031488
3                                         g__CAG-352  UP000018340
4                   g__Christensenellaceae R-7 group  UP000531233
..                                               ...          ...
408                           g__unknown_ Parvimonas  UP000031386
409                           g__unknown_ Parvimonas  UP000070197
410                        g__unknown_ Peptoniphilus  UP000250070
411                        g__unknown_ Peptoniphilus  UP000255517
414  g__unknown_ Eubacterium coprostanoligenes group  UP000002801

[460 rows x 2 columns]

In [9]:
os.makedirs("./data/proteomes", exist_ok=True)
tot = 0
for k, v in filt_df.iterrows():
    print(k, v["Proteome ID"])
    protFile = "./data/proteomes/" + "{}.pkl".format(v["Proteome ID"])
                    
    if not os.path.isfile(protFile):
        reviewed = list()

        req = "https://www.ebi.ac.uk/proteins/api/proteomes/proteins/{}?reviewed=True".format(v["Proteome ID"])
        r = requests.get(req)
        res = r.json()

        if "component" in res and len(res["component"]) > 0:
            if "protein" in res["component"][0]:
                for p in res["component"][0]["protein"]:
                    reviewed.append(p["accession"])
        
        unreviewed = list()

        req = "https://www.ebi.ac.uk/proteins/api/proteomes/proteins/{}?reviewed=False".format(v["Proteome ID"])
        r = requests.get(req)
        res = r.json()
        if "component" in res and len(res["component"]) > 0:
            if "protein" in res["component"][0]:
                for p in res["component"][0]["protein"]:
                    unreviewed.append(p["accession"])
        
        protList = reviewed + unreviewed
        protList = list(set(protList))

        with open(protFile, "wb") as fp:   
            pickle.dump(protList, fp)

0 UP000016519
1 UP000293036
2 UP000031488
3 UP000018340
4 UP000531233
5 UP000013051
6 UP000461734
7 UP000033457
8 UP000005332
9 UP000014577
10 UP000199355
11 UP000003277
12 UP000528555
13 UP000001006
14 UP000018069
15 UP000018868
16 UP000483027
17 UP000253976
18 UP000007468
19 UP000295711
20 UP000033124
21 UP000176615
22 UP000074544
23 UP000068137
24 UP000053091
25 UP000003045
26 UP000591941
27 UP000298358
28 UP000031461
29 UP000027946
30 UP000198995
31 UP000255233
32 UP000033103
33 UP000242432
34 UP000018843
35 UP000561134
36 UP000003821
37 UP000215624
38 UP000531233
39 UP000824078
40 UP000190657
41 UP000245793
42 UP000556020
43 UP000831151
44 UP000001319
45 UP000581150
46 UP000004191
47 UP000199158
48 UP000514720
49 UP000191179
50 UP000233535
51 UP000576402
52 UP000678348
53 UP000681387
54 UP000006605
55 UP000182805
56 UP000525652
57 UP000438537
58 UP000013893
59 UP000259231
60 UP000070542
61 UP000245959
62 UP000016618
0 UP000182379
1 UP000754226
2 UP000018195
3 UP000185603
4 UP000472380
5 UP000280168
6 UP000006087
7 UP000001031
8 UP000077642
9 UP000773393
10 UP000600429
11 UP000324870
12 UP000006008
13 UP000318946
14 UP000322940
15 UP000187417
16 UP000008794
17 UP000196483
18 UP000018329
19 UP000198813
20 UP000183253
21 UP000002960
22 UP000199689
23 UP000003460
24 UP000266506
25 UP000004935
26 UP000095553
27 UP000018385
28 UP000095765
29 UP000018024
30 UP000000960
31 UP000186810
32 UP000018228
33 UP000018187
34 UP000018293
35 UP000018390
36 UP000017907
37 UP000298073
38 UP000763371
39 UP000095657
40 UP000061809
41 UP000195386
42 UP000003146
43 UP000014073
44 UP000283678
45 UP000254424
46 UP000184436
47 UP000095606
48 UP000095517
49 UP000003416
50 UP000006731
51 UP000070319
52 UP000017831
53 UP000003089
54 UP000260983
55 UP000074719
56 UP000260780
57 UP000007486
58 UP000005150
59 UP000014200
60 UP000195946
61 UP000195734
62 UP000195322
63 UP000195527
64 UP000195786
65 UP000018098
66 UP000018063
67 UP000018392
68 UP000184192
69 UP000056419
70 UP000001414
71 UP000014212
72 UP000002861
73 UP000183040
74 UP000245793
75 UP000003136
76 UP000006044
77 UP000196204
78 UP000196624
79 UP000008702
80 UP000033737
81 UP000002456
82 UP000006173
83 UP000014395
84 UP000192666
85 UP000429211
86 UP000029046
87 UP000000439
88 UP000095326
89 UP000029033
90 UP000029003
91 UP000006034
92 UP000003718
93 UP000018315
94 UP000295817
95 UP000003755
96 UP000095625
97 UP000473323
98 UP000095409
99 UP000289794
100 UP000018056
101 UP000018177
102 UP000250003
103 UP000095431
104 UP000195326
105 UP000283589
106 UP000196559
107 UP000186985
108 UP000018075
109 UP000183950
110 UP000002407
111 UP000095723
112 UP000018308
113 UP000196418
114 UP000093044
115 UP000095441
116 UP000283983
117 UP000003560
118 UP000004830
119 UP000195399
120 UP000053300
121 UP000017988
122 UP000018297
123 UP000017997
124 UP000003157
125 UP000269493
126 UP000594042
128 UP000261231
129 UP000095362
130 UP000095519
132 UP000018002
133 UP000297065
134 UP000319704
135 UP000069241
136 UP000186323
137 UP000195838
138 UP000246125
139 UP000014960
141 UP000001377
142 UP000270112
143 UP000186117
144 UP000018393
145 UP000018266
146 UP000018088
147 UP000008929
148 UP000486668
149 UP000284286
150 UP000236012
151 UP000244140
152 UP000070452
153 UP000055269
154 UP000005798
155 UP000196550
157 UP000093409
158 UP000016858
159 UP000655907
160 UP000000625
161 UP000000745
162 UP000199324
163 UP000001476
164 UP000095492
165 UP000049472
166 UP000018142
167 UP000017940
168 UP000018404
169 UP000018005
170 UP000018124
171 UP000018318
172 UP000018411
173 UP000018194
174 UP000018414
175 UP000017904
176 UP000017954
177 UP000017975
178 UP000018312
179 UP000017924
180 UP000284779
181 UP000014176
183 UP000018132
184 UP000018328
185 UP000095722
186 UP000195447
187 UP000092639
188 UP000192328
189 UP000196537
190 UP000095366
191 UP000018397
192 UP000002975
193 UP000284676
194 UP000003092
195 UP000002521
196 UP000055238
197 UP000003748
198 UP000018095
199 UP000240458
200 UP000004505
201 UP000591197
202 UP000033339
203 UP000235670
204 UP000657609
205 UP000003016
206 UP000092740
207 UP000253945
208 UP000255264
209 UP000175677
210 UP000253872
211 UP000218796
212 UP000233350
213 UP000265489
214 UP000434241
215 UP000886845
216 UP000293400
217 UP000035284
218 UP000186372
220 UP000247485
221 UP000255382
222 UP000367200
223 UP000516181
224 UP000005039
225 UP000000370
226 UP000199786
227 UP000196620
228 UP000196089
229 UP000008804
230 UP000017395
231 UP000191179
232 UP000018092
233 UP000270861
234 UP000306101
235 UP000006850
236 UP000070507
237 UP000292818
238 UP000094714
239 UP000195859
240 UP000460112
241 UP000258174
242 UP000289414
243 UP000050973
244 UP000193009
245 UP000250714
246 UP000076164
247 UP000035323
248 UP000029488
249 UP000004483
250 UP000076519
251 UP000031847
252 UP000469952
253 UP000005963
254 UP000591071
255 UP000184179
256 UP000713808
257 UP000218586
258 UP000195529
259 UP000232133
260 UP000003489
261 UP000095546
262 UP000003671
263 UP000235589
264 UP000004892
265 UP000006657
266 UP000522163
267 UP000017942
268 UP000018113
270 UP000000566
271 UP000036166
272 UP000033035
273 UP000001218
274 UP000006271
275 UP000256321
276 UP000018199
277 UP000196154
278 UP000718459
279 UP000005546
280 UP000462362
281 UP000255101
282 UP000029560
283 UP000627493
284 UP000014944
285 UP000014925
286 UP000004923
287 UP000006545
288 UP000004295
289 UP000070224
290 UP000177035
291 UP000030103
292 UP000002786
293 UP000003112
294 UP000018361
295 UP000070533
296 UP000255469
297 UP000254072
298 UP000187195
299 UP000234283
300 UP000267517
301 UP000003874
302 UP000216632
303 UP000017987
304 UP000017956
305 UP000018054
306 UP000018111
307 UP000018046
308 UP000018116
309 UP000018359
310 UP000018295
311 UP000018057
312 UP000018039
313 UP000018147
314 UP000004407
315 UP000004001
316 UP000003327
317 UP000003829
318 UP000214740
320 UP000195540
321 UP000006462
322 UP000018292
323 UP000017909
324 UP000049979
325 UP000266172
326 UP000018030
327 UP000049828
329 UP000018104
330 UP000018336
331 UP000018355
332 UP000018173
333 UP000448177
334 UP000234812
335 UP000260793
336 UP000018123
338 UP000018166
339 UP000018243
340 UP000078383
341 UP000027600
342 UP000233562
343 UP000016662
344 UP000007054
345 UP000018181
346 UP000018315
347 UP000018377
348 UP000017936
349 UP000017925
351 UP000018082
352 UP000018387
353 UP000017977
354 UP000029601
355 UP000746411
356 UP000543804
357 UP000261080
358 UP000253792
359 UP000006001
360 UP000271472
361 UP000006069
362 UP000004097
363 UP000018360
364 UP000057897
365 UP000275354
366 UP000033711
367 UP000255352
368 UP000003291
369 UP000270905
370 UP000027992
371 UP000002512
372 UP000033657
373 UP000033547
374 UP000261141
375 UP000191231
376 UP000271902
377 UP000017124
378 UP000249634
379 UP000380217
380 UP000017993
381 UP000004956
382 UP000018289
383 UP000284958
384 UP000014400
387 UP000006852
388 UP000095452
389 UP000018368
390 UP000070226
391 UP000238899
392 UP000707138
393 UP000234458
394 UP000238774
395 UP000434554
396 UP000303581
397 UP000245959
398 UP000032287
399 UP000284176
400 UP000786190
401 UP000078495
402 UP000018094
406 UP000243008
407 UP000266993
408 UP000031386
409 UP000070197
410 UP000250070
411 UP000255517
414 UP000002801

In [12]:
filt_df["Proteome ID"].nunique()

455

In [11]:
filt_df["Genus"].nunique()

165

In [13]:
# Construct the bac_info_dir. Key1: genus, key2: proteome ID and value: list of proteins

bac_info_dir = {}
for k, v in filt_df.iterrows():
    if v["Genus"] in bac_info_dir:
        bac_info_dir[v["Genus"]][v["Proteome ID"]] = list()
    else:
        bac_info_dir[v["Genus"]] = {}
        bac_info_dir[v["Genus"]][v["Proteome ID"]] = list()
    protFile = "./data/proteomes/" + "{}.pkl".format(v["Proteome ID"])
    with open(protFile, "rb") as fp:
        protList = pickle.load(fp)
    bac_info_dir[v["Genus"]][v["Proteome ID"]] = protList


# Save to json
with open("./data/bac_info.json", "w") as fp:
    json.dump(bac_info_dir, fp, indent=4)

In [14]:
proteins = set()
for genus, proteome_dict in bac_info_dir.items():
    print(genus, len(proteome_dict))
    for proteome, prot_list in proteome_dict.items():
        print(proteome, len(prot_list))
        proteins.update(prot_list)
print(len(proteins))

g__Alloscardovia 1
UP000016519 1649
g__Arcanobacterium 1
UP000293036 1664
g__Brevibacterium 1
UP000031488 3434
g__CAG-352 1
UP000018340 0
g__Christensenellaceae R-7 group 1
UP000531233 1884
g__Clostridium innocuum group 1
UP000013051 4653
g__Colidextribacter 1
UP000461734 3624
g__Corynebacterium 2
UP000033457 2047
UP000029601 1151
g__Cutibacterium 1
UP000005332 2376
g__Dermabacter 1
UP000014577 2120
g__Desulfovibrio 8
UP000199355 2277
UP000297065 2637
UP000319704 0
UP000069241 3007
UP000186323 2530
UP000195838 2772
UP000246125 3095
UP000014960 3444
g__Dialister 1
UP000003277 2140
g__Dorea 1
UP000528555 2205
g_Shigella 1
UP000001006 3859
g__Eubacterium hallii group 2
UP000018069 0
UP000014176 3773
g__Eubacterium nodatum group 3
UP000018868 1690
UP000002521 2046
UP000055238 0
g__Facklamia 1
UP000483027 1842
g__Family XIII AD3011 group 1
UP000253976 1520
g__Filifactor 1
UP000007468 1615
g__Frisingicoccus 1
UP000295711 2610
g__Gardnerella 1
UP000033124 0
g__Globicatella 1
UP000176615 2027
g__Obesumbacterium 1
UP000074544 0
g__Lawsonella 1
UP000068137 1376
g__Lentimicrobium 1
UP000053091 3377
g__Mobiluncus 1
UP000003045 0
g__Negativicoccus 1
UP000591941 1389
g__Paludicola 1
UP000298358 3006
g__Pedobacter 1
UP000031461 0
g__Peptoclostridium 1
UP000027946 2948
g__Peptococcus 1
UP000198995 1844
g__Rikenellaceae RC9 gut group 1
UP000255233 2358
g__Sneathia 1
UP000033103 1182
g__Succinivibrio 1
UP000242432 2306
g__Varibaculum 1
UP000018843 0
g__unknown_ Actinomycetaceae 1
UP000561134 1795
g__unknown_ Anaerococcus 1
UP000003821 1764
g__unknown_ Burkholderiales 1
UP000215624 0
g__unknown_ Christensenellaceae 1
UP000531233 1884
g__unknown_ Coriobacteriales Incertae Sedis 1
UP000824078 1561
g__unknown_ Eubacterium coprostanoligenes group 2
UP000190657 1647
UP000002801 2987
g__unknown_ Ezakiella 1
UP000245793 1626
g__unknown_ Fastidiosipila 1
UP000556020 1484
g__unknown_ Fenollaria 1
UP000831151 1438
g__unknown_ Finegoldia 1
UP000001319 1631
g__unknown_ Gallicola 1
UP000581150 1851
g__unknown_ Helcococcus 1
UP000004191 1876
g__unknown_ Hydrogenoanaerobacterium 2
UP000199158 2929
UP000095625 0
g__unknown_ Izemoplasmatales 1
UP000514720 1861
g__unknown_ Lachnospiraceae 1
UP000191179 3259
g__unknown_ Marinifilaceae 1
UP000233535 4006
g__unknown_ Micrococcaceae 1
UP000576402 2961
g__unknown_ Oscillospiraceae 1
UP000678348 2755
g__unknown_ Peptococcaceae 1
UP000681387 2380
g__unknown_ Peptostreptococcaceae 1
UP000006605 2299
g__unknown_ Prevotellaceae 1
UP000182805 2311
g__unknown_ Puniceicoccaceae 1
UP000525652 4123
g__unknown_ Rhodospirillales 1
UP000438537 7065
g__unknown_ Saccharimonadales 1
UP000013893 1033
g__unknown_ Synergistaceae 1
UP000259231 1569
g__unknown_ Veillonellaceae 1
UP000070542 1608
g__unknown_ Victivallaceae 1
UP000245959 4059
g__unknown_ W5053 1
UP000016618 2325
g__Acidaminococcus 3
UP000182379 2052
UP000754226 1891
UP000018195 1849
g__Actinomyces 1
UP000185603 0
g__Adlercreutzia 1
UP000472380 2198
g__Aeromonas 2
UP000280168 0
UP000006087 4109
g__Akkermansia 4
UP000001031 2137
UP000077642 0
UP000773393 0
UP000600429 2518
g__Alistipes 11
UP000324870 0
UP000006008 2348
UP000318946 2673
UP000322940 3215
UP000187417 2038
UP000008794 2563
UP000196483 2054
UP000018329 2200
UP000198813 2504
UP000183253 2701
UP000002960 2955
g__Allisonella 1
UP000199689 1536
g__Alloprevotella 1
UP000003460 2806
g__Anaeroplasma 1
UP000266506 1953
g__Anaerostipes 2
UP000004935 3743
UP000095553 3010
g__Anaerotruncus 3
UP000018385 2237
UP000095765 3729
UP000018024 0
g__Atopobium 1
UP000000960 1353
g__Bacteroides 39
UP000186810 3807
UP000018228 0
UP000018187 0
UP000018293 0
UP000018390 0
UP000017907 2231
UP000298073 4063
UP000763371 0
UP000095657 4410
UP000195386 3443
UP000003146 4095
UP000283678 4637
UP000254424 3557
UP000095606 5029
UP000095517 3498
UP000003416 3920
UP000006731 4187
UP000017831 3865
UP000003089 4388
UP000260983 4686
UP000074719 0
UP000260780 3494
UP000007486 3520
UP000005150 4569
UP000014200 4485
UP000195946 3999
UP000195734 3729
UP000195322 3165
UP000195527 2802
UP000195786 3560
UP000018098 2710
UP000018063 2834
UP000018392 2669
UP000184192 4982
UP000056419 3155
UP000014212 3957
UP000002861 3982
UP000183040 4799
UP000245793 1626
g__Bacteroides pectinophilus group 8
UP000061809 5462
UP000014073 3838
UP000184436 4051
UP000070319 5598
UP000001414 4744
UP000003136 3243
UP000295817 0
UP000018094 2179
g__Barnesiella 2
UP000006044 2808
UP000196204 2716
g__unknown_ Barnesiellaceae 1
UP000196624 2412
g__Bifidobacterium 15
UP000008702 1629
UP000033737 0
UP000002456 1525
UP000006173 1834
UP000014395 0
UP000192666 1749
UP000429211 2354
UP000029046 1652
UP000000439 1723
UP000095326 0
UP000029033 2477
UP000029003 1823
UP000591197 1913
UP000033339 65
UP000293400 5266
g__Bilophila 2
UP000006034 3779
UP000003718 4113
g__Ruminococcus_g2 6
UP000018315 0
UP000018166 1853
UP000018243 0
UP000018181 0
UP000017936 2331
UP000017977 0
g__Blautia 8
UP000003755 3170
UP000473323 3159
UP000095409 3072
UP000289794 5475
UP000018056 0
UP000018177 0
UP000250003 2737
UP000095431 3715
g__Butyricicoccus 1
UP000195326 3188
g__Butyricimonas 2
UP000283589 4212
UP000196559 3969
g__Butyrivibrio 2
UP000186985 0
UP000018075 2127
g__Campylobacter 2
UP000183950 0
UP000002407 1682
g__Catenibacterium 3
UP000095723 0
UP000018308 1992
UP000199324 3682
g__Cloacibacillus 2
UP000196418 2713
UP000093044 3049
g__Collinsella 5
UP000095441 0
UP000283983 1430
UP000003560 2527
UP000004830 2204
UP000195399 2074
g__Comamonas 1
UP000053300 2662
g__Coprobacillus 4
UP000017988 0
UP000018297 0
UP000017997 0
UP000003157 3839
g__Coprobacter 2
UP000269493 2668
UP000594042 3272
g__Coprococcus 4
UP000261231 3079
UP000095362 3091
UP000095519 0
UP000018002 0
g__Eggerthella 7
UP000001377 3054
UP000270112 3438
UP000186117 1387
UP000018393 0
UP000018266 1581
UP000018088 1381
UP000008929 2674
g__unknown_ Eggerthellaceae 1
UP000486668 1967
g__Enterococcus 5
UP000284286 0
UP000236012 0
UP000244140 3406
UP000070452 3084
UP000055269 0
g__Erysipelatoclostridium 2
UP000005798 3166
UP000196550 2792
g__Erysipelotrichaceae UCG-003 2
UP000093409 2314
UP000016858 2871
g__unknown_ Erysipelotrichaceae 1
UP000655907 2404
g__Escherichia-Shigella 2
UP000000625 4402
UP000000745 4256
g__Eubacterium eligens group 4
UP000001476 2003
UP000017940 2189
UP000018312 2287
UP000591071 2484
g__Eubacterium siraeum group 3
UP000095492 2955
UP000018142 2308
UP000191179 3259
g__Eubacterium 11
UP000049472 2859
UP000018404 0
UP000018005 2289
UP000018124 0
UP000018318 0
UP000018411 1742
UP000018194 0
UP000017904 2006
UP000017954 2436
UP000017975 0
UP000017924 1649
g__Eubacterium ventriosum group 2
UP000018414 1717
UP000284779 2182
g__Faecalibacterium 3
UP000018132 1284
UP000018328 0
UP000095722 0
g__Faecalitalea 1
UP000195447 1972
g__Flavonifractor 4
UP000092639 0
UP000192328 3011
UP000196537 3501
UP000271472 1842
g__Fusicatenibacter 1
UP000095366 0
g__Fusobacterium 8
UP000018397 2311
UP000002975 1890
UP000284676 2495
UP000003092 0
UP000003748 2565
UP000018095 1820
UP000240458 0
UP000004505 0
g__Gemella 1
UP000235670 1747
g__Granulicatella 1
UP000657609 0
g__Haemophilus 6
UP000003016 0
UP000092740 1997
UP000253945 1819
UP000255264 2032
UP000175677 0
UP000253872 2065
g__Hafnia-Obesumbacterium 1
UP000218796 4446
g__Helicobacter 1
UP000233350 1590
g__Holdemanella 2
UP000265489 2529
UP000434241 1957
g__Megasphaera 5
UP000886845 1583
UP000184179 0
UP000713808 0
UP000218586 2367
UP000195529 2144
g__Klebsiella 6
UP000035284 0
UP000186372 0
UP000247485 5789
UP000255382 6726
UP000367200 0
UP000516181 137
g__Lachnoanaerobaculum 1
UP000005039 3005
g__Lachnoclostridium 5
UP000000370 3891
UP000199786 3184
UP000196620 3410
UP000196089 3897
UP000008804 2755
g__Lachnospiraceae UCG-003 2
UP000017395 3455
UP000018092 0
g__Lactobacillus 17
UP000270861 0
UP000306101 0
UP000006850 0
UP000070507 0
UP000292818 1905
UP000094714 1789
UP000195859 1873
UP000460112 1751
UP000258174 0
UP000289414 0
UP000050973 1862
UP000193009 2624
UP000250714 0
UP000076164 0
UP000035323 0
UP000029488 112
UP000004483 1870
g__Lactococcus 2
UP000076519 2278
UP000031847 3114
g__Leuconostoc 1
UP000469952 1889
g__Megamonas 1
UP000005963 0
g__Methanobrevibacter 2
UP000232133 1683
UP000003489 1709
g__Mitsuokella 2
UP000095546 2093
UP000003671 2558
g__Monoglobus 1
UP000235589 2258
g__Odoribacter 2
UP000004892 3097
UP000006657 3479
g__Oribacterium 1
UP000522163 2377
g__Oscillibacter 2
UP000017942 2148
UP000018113 0
g__Parabacteroides 8
UP000000566 3830
UP000036166 5253
UP000033035 5316
UP000001218 3736
UP000006271 4104
UP000256321 3949
UP000018199 2823
UP000196154 2949
g__Paraprevotella 2
UP000718459 0
UP000005546 3442
g__Parasutterella 1
UP000462362 2579
g__Peptostreptococcus 3
UP000255101 1984
UP000029560 1619
UP000627493 0
g__Phascolarctobacterium 3
UP000014944 0
UP000014925 1778
UP000004923 2148
g__Porphyromonas 5
UP000006545 1672
UP000004295 1965
UP000070224 2194
UP000177035 1615
UP000030103 1843
g__Prevotella 16
UP000002786 2064
UP000003112 2896
UP000018361 0
UP000070533 2956
UP000255469 2539
UP000254072 2524
UP000187195 0
UP000234283 0
UP000267517 1376
UP000003874 2938
UP000216632 2874
UP000018116 0
UP000004407 3016
UP000004001 2202
UP000003327 3037
UP000003829 2926
g__Prevotellaceae UCG-001 9
UP000017987 2513
UP000017956 2441
UP000018054 2562
UP000018111 2035
UP000018359 2171
UP000018295 0
UP000018057 1928
UP000018147 2058
UP000214740 2620
g__Prevotellaceae UCG-003 2
UP000018046 2132
UP000018039 2409
g__Proteus 1
UP000195540 3904
g__Pyramidobacter 1
UP000006462 0
g__Roseburia 10
UP000018292 2223
UP000017909 2486
UP000049979 3168
UP000266172 3234
UP000018030 0
UP000049828 3442
UP000018104 2523
UP000018336 2420
UP000018355 2401
UP000018173 0
g__Ruminococcus 12
UP000448177 2947
UP000234812 0
UP000260793 2735
UP000027600 0
UP000233562 0
UP000016662 3475
UP000007054 2114
UP000018315 0
UP000018377 0
UP000017925 0
UP000018082 2054
UP000018387 2155
g__Ruminococcus torques group 2
UP000018123 2160
UP000078383 2761
g__Selenomonas 2
UP000746411 0
UP000543804 2072
g__Senegalimassilia 2
UP000261080 3054
UP000253792 1843
g__Slackia 2
UP000006001 2027
UP000006069 1794
g__Solobacterium 1
UP000004097 2034
g__Staphylococcus 1
UP000018360 0
g__Streptococcus 16
UP000057897 0
UP000275354 0
UP000033711 0
UP000255352 1938
UP000003291 0
UP000270905 0
UP000027992 0
UP000002512 1953
UP000033657 1816
UP000033547 0
UP000261141 0
UP000191231 0
UP000271902 0
UP000017124 0
UP000249634 2239
UP000380217 1896
g__Subdoligranulum 1
UP000017993 1341
g__Sutterella 4
UP000004956 2483
UP000018289 1632
UP000284958 1912
UP000014400 2393
g__Treponema 1
UP000006852 2413
g__Turicibacter 1
UP000095452 0
g__Tyzzerella 1
UP000018368 0
g__Veillonella 7
UP000070226 1973
UP000238899 0
UP000707138 0
UP000234458 0
UP000238774 0
UP000434554 2032
UP000303581 1869
g__Victivallis 1
UP000245959 4059
g__Weissella 2
UP000032287 2282
UP000284176 0
g__unknown_ Atopobiaceae 1
UP000786190 979
g__unknown_ Bacteroidales 1
UP000078495 3840
g__unknown_ Gastranaerophilales 1
UP000243008 1073
g__unknown_ Muribaculaceae 1
UP000266993 2513
g__unknown_ Parvimonas 2
UP000031386 1418
UP000070197 1524
g__unknown_ Peptoniphilus 2
UP000250070 2081
UP000255517 1740
904554

In [17]:
# Write the bacterial proteins to a txt
with open("./data/bacterial_proteins.txt", "w") as fp:
    for prot in proteins:
        fp.write(prot + "\n")

# Slice them in batches of 90000 and write them to different files
for i in range(0, len(proteins), 90000):
    prot_batch = list(proteins)[i:i+90000]
    with open("./data/bacterial_proteins_batch_" + str(i) + ".txt", "w") as fp:
        for prot in prot_batch:
            fp.write(prot + "\n")

*...*

**Wait for the Uniprot Mapping**

Under data/bac_mapping

**...**

In [37]:
df_list = list()
for mapping_file in os.listdir("./data/bac_mapping"):
    # Read all .tsv.gz files
    mapping_df = pd.read_csv("./data/bac_mapping/" + mapping_file, sep="\t", compression="gzip")
    # Append to df_list
    df_list.append(mapping_df)

bac_prots_df = pd.concat(df_list, axis=0)
bac_prots_df

,From,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Sequence
0,R5N1R7,R5N1R7,unreviewed,R5N1R7_9FIRM,Elongation factor Ts (EF-Ts),tsf BN519_00791,Eubacterium sp. CAG:180,309,MAFTASDVKALREKTGVGMMDCKKALVESDGDMDKAIDFLREKGLA...
1,A0A173W6J8,A0A173W6J8,unreviewed,A0A173W6J8_9FIRM,Ribonuclease PH (RNase PH) (EC 2.7.7.56) (tRNA...,rph ERS852385_00019,Mitsuokella jalaludinii,248,MTRTDRRMADALRPYEIHRHFQKYPAGSVLIEMGNTKVICAASIED...
2,Q8R602,Q8R602,reviewed,EFG_FUSNN,Elongation factor G (EF-G),fusA FN1556,Fusobacterium nucleatum subsp. nucleatum (stra...,693,MARKISLDMTRNVGIMAHIDAGKTTTTERILFYTGVERKLKEVHEG...
3,C7HTX5,C7HTX5,unreviewed,C7HTX5_9FIRM,histidine kinase (EC 2.7.13.3),phoR HMPREF0078_0726,Anaerococcus vaginalis ATCC 51170,479,MEIEKKKKSLFKINFNSIIFSIMKIIMIFVTLVVVGFEIFSYRSIT...
4,R6V9Z1,R6V9Z1,unreviewed,R6V9Z1_9FIRM,Cell division protein SepF,sepF BN635_02018,Roseburia sp. CAG:380,193,MANPLGNLLQLLRLGDDEDYDDDYYEDDFEDDIDEEEERSLLAEEQ...
...,...,...,...,...,...,...,...,...,...
89995,R9HSW2,R9HSW2,unreviewed,R9HSW2_BACUN,Lon protease (EC 3.4.21.53) (ATP-dependent pro...,lon C801_02872,Bacteroides uniformis dnLKV2,826,MKKRNYLSDVEDRNGNAFSVIADFEGNEEQLMDIEVEEVLPILPLR...
89996,A0A6I3RXL6,A0A6I3RXL6,unreviewed,A0A6I3RXL6_9BURK,D-glycero-beta-D-manno-heptose 1-phosphate ade...,rfaE2 GMD42_01825,Parasutterella excrementihominis,164,MSQHLPPPPFEKKIVSFEKLEEFVRKLPHPVVLTNGVFDILHRGHV...
89997,Q8A4L3,Q8A4L3,unreviewed,Q8A4L3_BACTN,Uncharacterized protein,BT_2586,Bacteroides thetaiotaomicron (strain ATCC 2914...,167,MEEWIQYARDMAKAEKELEIELWVIISFYRTTEQGGKVLLFRYDLP...
89998,A0A173T8G7,A0A173T8G7,unreviewed,A0A173T8G7_9FIRM,Cell division topological specificity factor MinE,comes_20010 DW252_07705 DW656_00130 DWW65_0524...,Coprococcus comes,76,MHVFERGMHHSSVRIAKERLKSLLVSDRVQCQPDTYELLCGELYHT...
89999,A0A2A2IIU4,A0A2A2IIU4,unreviewed,A0A2A2IIU4_9FIRM,Transposase,CJ260_12525,Megasphaera sp. ASD88,140,LKRSRSRKEYSFEEKLSVVESYLTSELSYQELALQMGINNPSMLAR...

In [38]:
# Drop NaN for Sequence
bac_prots_df = bac_prots_df.dropna(subset=["Sequence"])
bac_prots_df = bac_prots_df.reset_index(drop=True)
bac_prots_df

,From,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Sequence
0,R5N1R7,R5N1R7,unreviewed,R5N1R7_9FIRM,Elongation factor Ts (EF-Ts),tsf BN519_00791,Eubacterium sp. CAG:180,309,MAFTASDVKALREKTGVGMMDCKKALVESDGDMDKAIDFLREKGLA...
1,A0A173W6J8,A0A173W6J8,unreviewed,A0A173W6J8_9FIRM,Ribonuclease PH (RNase PH) (EC 2.7.7.56) (tRNA...,rph ERS852385_00019,Mitsuokella jalaludinii,248,MTRTDRRMADALRPYEIHRHFQKYPAGSVLIEMGNTKVICAASIED...
2,Q8R602,Q8R602,reviewed,EFG_FUSNN,Elongation factor G (EF-G),fusA FN1556,Fusobacterium nucleatum subsp. nucleatum (stra...,693,MARKISLDMTRNVGIMAHIDAGKTTTTERILFYTGVERKLKEVHEG...
3,C7HTX5,C7HTX5,unreviewed,C7HTX5_9FIRM,histidine kinase (EC 2.7.13.3),phoR HMPREF0078_0726,Anaerococcus vaginalis ATCC 51170,479,MEIEKKKKSLFKINFNSIIFSIMKIIMIFVTLVVVGFEIFSYRSIT...
4,R6V9Z1,R6V9Z1,unreviewed,R6V9Z1_9FIRM,Cell division protein SepF,sepF BN635_02018,Roseburia sp. CAG:380,193,MANPLGNLLQLLRLGDDEDYDDDYYEDDFEDDIDEEEERSLLAEEQ...
...,...,...,...,...,...,...,...,...,...
904549,R9HSW2,R9HSW2,unreviewed,R9HSW2_BACUN,Lon protease (EC 3.4.21.53) (ATP-dependent pro...,lon C801_02872,Bacteroides uniformis dnLKV2,826,MKKRNYLSDVEDRNGNAFSVIADFEGNEEQLMDIEVEEVLPILPLR...
904550,A0A6I3RXL6,A0A6I3RXL6,unreviewed,A0A6I3RXL6_9BURK,D-glycero-beta-D-manno-heptose 1-phosphate ade...,rfaE2 GMD42_01825,Parasutterella excrementihominis,164,MSQHLPPPPFEKKIVSFEKLEEFVRKLPHPVVLTNGVFDILHRGHV...
904551,Q8A4L3,Q8A4L3,unreviewed,Q8A4L3_BACTN,Uncharacterized protein,BT_2586,Bacteroides thetaiotaomicron (strain ATCC 2914...,167,MEEWIQYARDMAKAEKELEIELWVIISFYRTTEQGGKVLLFRYDLP...
904552,A0A173T8G7,A0A173T8G7,unreviewed,A0A173T8G7_9FIRM,Cell division topological specificity factor MinE,comes_20010 DW252_07705 DW656_00130 DWW65_0524...,Coprococcus comes,76,MHVFERGMHHSSVRIAKERLKSLLVSDRVQCQPDTYELLCGELYHT...
904553,A0A2A2IIU4,A0A2A2IIU4,unreviewed,A0A2A2IIU4_9FIRM,Transposase,CJ260_12525,Megasphaera sp. ASD88,140,LKRSRSRKEYSFEEKLSVVESYLTSELSYQELALQMGINNPSMLAR...

In [39]:
# Save 
bac_prots_df.to_csv("./data/bac_proteins.csv", index=False)

### Human protein (Gut and Brain Axis)

In [29]:
# Read gut and brain human data
gut = pd.read_csv(human_gut)
brain = pd.read_csv(human_brain)
# Concatenate gut and brain
gut_brain = pd.concat([gut, brain], axis=0)
# Drop duplicates
gut_brain = gut_brain.drop_duplicates()

# Get gene names
gene_names = gut_brain["Gene name"].unique()

# Write them to a txt
with open("./data/human_gene_names.txt", "w") as fp:
    for gene in gene_names:
        fp.write(gene + "\n")

*...*

**Wait for the Uniprot Mapping**

**...**

In [31]:
human_gut_brain = "./data/gut_c3/human_gut_brain.tsv.gz"

# Read gut and brain human data
gut_brain = pd.read_csv(human_gut_brain, sep="\t")
gut_brain

,From,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Sequence
0,TSPAN6,O43657,reviewed,TSN6_HUMAN,Tetraspanin-6 (Tspan-6) (A15 homolog) (Putativ...,TSPAN6 TM4SF6 UNQ767/PRO1560,Homo sapiens (Human),245,MASPSRRLQTKPVITCFKSVLLIYTFIFWITGVILLAVGIWGKVSL...
1,TSPAN6,A0A087WYV6,unreviewed,A0A087WYV6_HUMAN,Tetraspanin-6,TSPAN6,Homo sapiens (Human),129,MLKLYAMFLTLVFLVELVAAIVGFVFRHEIKNSFKNNYEKALKQYN...
2,DPM1,O60762,reviewed,DPM1_HUMAN,Dolichol-phosphate mannosyltransferase subunit...,DPM1,Homo sapiens (Human),260,MASLEVSRSPRRSRRELEVRSPRQNKYSVLLPTYNERENLPLIVWL...
3,DPM1,A0A0S2Z4U1,unreviewed,A0A0S2Z4U1_HUMAN,Dolichol-phosphate mannosyltransferase subunit...,DPM1,Homo sapiens (Human),133,MASLEVSRSPRRSRRELEVRSPRQNKYSVLLPTYNERENLPLIVWL...
4,DPM1,A0A0S2Z4Y5,unreviewed,A0A0S2Z4Y5_HUMAN,Dolichol-phosphate mannosyltransferase subunit...,DPM1,Homo sapiens (Human),260,MASLEVSRSPRRSRRELEVRSPRQNKYSVLLPTYNERENLPLIVWL...
...,...,...,...,...,...,...,...,...,...
83381,GRIN2B,A0A0D9SFA0,unreviewed,A0A0D9SFA0_HUMAN,Glutamate ionotropic receptor NMDA type subuni...,GRIN2B,Homo sapiens (Human),35,MKPRAECCSPKFWLVLAVLAVSGSRARSQKSPPSI
83382,GRIN2B,A0A0D9SFK0,unreviewed,A0A0D9SFK0_HUMAN,Glutamate ionotropic receptor NMDA type subuni...,GRIN2B,Homo sapiens (Human),464,MKPRAECCSPKFWLVLAVLAVSGSRARSQKSPPSIGIAVILVGTSD...
83383,GRIN2B,A0A1B0GU78,unreviewed,A0A1B0GU78_HUMAN,Glutamate ionotropic receptor NMDA type subuni...,GRIN2B,Homo sapiens (Human),46,ANLAAFMIQEEYVDQVSGLSDKKMRTLRLRRSIFPKVTKLVTEPGF
83384,GRIN2B,A0A8D9PHB2,unreviewed,A0A8D9PHB2_HUMAN,Glutamate receptor,GRIN2B hCG_1811072,Homo sapiens (Human),1484,MKPRAECCSPKFWLVLAVLAVSGSRARSQKSPPSIGIAVILVGTSD...
83385,GRIN2B,A0AAQ5BH89,unreviewed,A0AAQ5BH89_HUMAN,Glutamate receptor,GRIN2B,Homo sapiens (Human),677,MKPRAECCSPKFWLVLAVLAVSGSRARSQKSPPSIGIAVILVGTSD...

In [32]:
# Keep only reviewed
gut_brain = gut_brain[gut_brain["Reviewed"] == "reviewed"].reset_index(drop=True)
gut_brain

,From,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Sequence
0,TSPAN6,O43657,reviewed,TSN6_HUMAN,Tetraspanin-6 (Tspan-6) (A15 homolog) (Putativ...,TSPAN6 TM4SF6 UNQ767/PRO1560,Homo sapiens (Human),245,MASPSRRLQTKPVITCFKSVLLIYTFIFWITGVILLAVGIWGKVSL...
1,DPM1,O60762,reviewed,DPM1_HUMAN,Dolichol-phosphate mannosyltransferase subunit...,DPM1,Homo sapiens (Human),260,MASLEVSRSPRRSRRELEVRSPRQNKYSVLLPTYNERENLPLIVWL...
2,SCYL3,Q8IZE3,reviewed,PACE1_HUMAN,Protein-associating with the carboxyl-terminal...,SCYL3 PACE1,Homo sapiens (Human),742,MGSENSALKSYTLREPPFTLPSGLAVYPAVLQDGKFASVFVYKREN...
3,GCLC,P48506,reviewed,GSH1_HUMAN,Glutamate--cysteine ligase catalytic subunit (...,GCLC GLCL GLCLC,Homo sapiens (Human),637,MGLLSQGSPLSWEETKRHADHVRRHGILQFLHIYHAVKDRHKDVLK...
4,NFYA,P23511,reviewed,NFYA_HUMAN,Nuclear transcription factor Y subunit alpha (...,NFYA,Homo sapiens (Human),347,MEQYTANSNSSTEQIVVQAGQIQQQQQGGVTAVQLQTEAQVASASG...
...,...,...,...,...,...,...,...,...,...
10040,HS3ST5,Q96QI5,reviewed,HS3S6_HUMAN,Heparan sulfate glucosamine 3-O-sulfotransfera...,HS3ST6 HS3ST5,Homo sapiens (Human),342,MAGSGGLGGGAGGGQGAGAGQGAALRASRAPMLLVALVLGAYCLCA...
10041,YJEFN3,A6XGL0,reviewed,YJEN3_HUMAN,YjeF N-terminal domain-containing protein 3 (Y...,YJEFN3 AIBP2,Homo sapiens (Human),299,MSSAAGPDPSEAPEERHFLRALELQPPLADMGRAELSSNATTSLVQ...
10042,GPR162,Q16538,reviewed,GP162_HUMAN,Probable G-protein coupled receptor 162 (Gene-...,GPR162 GRCA,Homo sapiens (Human),588,MARGGAGAEEASLRSNALSWLACGLLALLANAWIILSISAKQQKHK...
10043,MIA,Q16674,reviewed,MIA_HUMAN,Melanoma-derived growth regulatory protein (Me...,MIA,Homo sapiens (Human),131,MARSLVCLGVIILLSAFSGPGVRGGPMPKLADRKLCADQECSHPIS...
10044,GRIN2B,Q13224,reviewed,NMDE2_HUMAN,"Glutamate receptor ionotropic, NMDA 2B (GluN2B...",GRIN2B NMDAR2B,Homo sapiens (Human),1484,MKPRAECCSPKFWLVLAVLAVSGSRARSQKSPPSIGIAVILVGTSD...

In [33]:
# Remove duplicates
gut_brain = gut_brain.drop_duplicates(subset=["Entry"]).reset_index(drop=True)
gut_brain

,From,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Sequence
0,TSPAN6,O43657,reviewed,TSN6_HUMAN,Tetraspanin-6 (Tspan-6) (A15 homolog) (Putativ...,TSPAN6 TM4SF6 UNQ767/PRO1560,Homo sapiens (Human),245,MASPSRRLQTKPVITCFKSVLLIYTFIFWITGVILLAVGIWGKVSL...
1,DPM1,O60762,reviewed,DPM1_HUMAN,Dolichol-phosphate mannosyltransferase subunit...,DPM1,Homo sapiens (Human),260,MASLEVSRSPRRSRRELEVRSPRQNKYSVLLPTYNERENLPLIVWL...
2,SCYL3,Q8IZE3,reviewed,PACE1_HUMAN,Protein-associating with the carboxyl-terminal...,SCYL3 PACE1,Homo sapiens (Human),742,MGSENSALKSYTLREPPFTLPSGLAVYPAVLQDGKFASVFVYKREN...
3,GCLC,P48506,reviewed,GSH1_HUMAN,Glutamate--cysteine ligase catalytic subunit (...,GCLC GLCL GLCLC,Homo sapiens (Human),637,MGLLSQGSPLSWEETKRHADHVRRHGILQFLHIYHAVKDRHKDVLK...
4,NFYA,P23511,reviewed,NFYA_HUMAN,Nuclear transcription factor Y subunit alpha (...,NFYA,Homo sapiens (Human),347,MEQYTANSNSSTEQIVVQAGQIQQQQQGGVTAVQLQTEAQVASASG...
...,...,...,...,...,...,...,...,...,...
9859,HS3ST5,Q96QI5,reviewed,HS3S6_HUMAN,Heparan sulfate glucosamine 3-O-sulfotransfera...,HS3ST6 HS3ST5,Homo sapiens (Human),342,MAGSGGLGGGAGGGQGAGAGQGAALRASRAPMLLVALVLGAYCLCA...
9860,YJEFN3,A6XGL0,reviewed,YJEN3_HUMAN,YjeF N-terminal domain-containing protein 3 (Y...,YJEFN3 AIBP2,Homo sapiens (Human),299,MSSAAGPDPSEAPEERHFLRALELQPPLADMGRAELSSNATTSLVQ...
9861,GPR162,Q16538,reviewed,GP162_HUMAN,Probable G-protein coupled receptor 162 (Gene-...,GPR162 GRCA,Homo sapiens (Human),588,MARGGAGAEEASLRSNALSWLACGLLALLANAWIILSISAKQQKHK...
9862,MIA,Q16674,reviewed,MIA_HUMAN,Melanoma-derived growth regulatory protein (Me...,MIA,Homo sapiens (Human),131,MARSLVCLGVIILLSAFSGPGVRGGPMPKLADRKLCADQECSHPIS...
9863,GRIN2B,Q13224,reviewed,NMDE2_HUMAN,"Glutamate receptor ionotropic, NMDA 2B (GluN2B...",GRIN2B NMDAR2B,Homo sapiens (Human),1484,MKPRAECCSPKFWLVLAVLAVSGSRARSQKSPPSIGIAVILVGTSD...

In [34]:
# Save to csv
gut_brain.to_csv("./data/human_gut_brain_proteins.csv", index=False)

In [44]:
# Final stats

# Number of bacterial proteins
bac_proteins = bac_prots_df["Entry"].unique().tolist()
print("Number of bacterial proteins:", len(bac_proteins))

# Number of human proteins
human_proteins = gut_brain["Entry"].unique().tolist()
print("Number of human proteins:", len(human_proteins))

# Number of potential PPIs
print("Number of potential PPIs:", len(bac_proteins) * len(human_proteins))

Number of bacterial proteins: 904554
Number of human proteins: 9864
Number of potential PPIs: 8922520656