In [1]:
import pandas as pd

In [2]:
file1 = "/home/c3biolab/c3biolab_projects/doctorals/DPK/c3ppi/notebooks/GUT_MB_Clinical/data/idmapping_chem_exp.tsv"
file2 = "/home/c3biolab/c3biolab_projects/doctorals/DPK/c3ppi/notebooks/GUT_MB_Clinical/data/idmapping_chem_exp_2.tsv"
file_nfkb = "/home/c3biolab/c3biolab_projects/doctorals/DPK/c3ppi/notebooks/GUT_MB_Clinical/data/idmapping_chem_exp_NFKB.tsv"

In [3]:
df1 = pd.read_csv(file1, sep="\t", header=0)
df1

,From,Entry,Protein names,Gene Ontology (molecular function),Gene Ontology (biological process)
0,COX1,P23219,Prostaglandin G/H synthase 1 (EC 1.14.99.1) (C...,heme binding [GO:0020037]; metal ion binding [...,cyclooxygenase pathway [GO:0019371]; long-chai...
1,COX1,A0A023I8C2,Cytochrome c oxidase subunit 1 (EC 7.1.1.9),cytochrome-c oxidase activity [GO:0004129]; he...,oxidative phosphorylation [GO:0006119]
2,COX1,A0A023I8E0,Cytochrome c oxidase subunit 1 (EC 7.1.1.9),cytochrome-c oxidase activity [GO:0004129]; he...,oxidative phosphorylation [GO:0006119]
3,COX1,A0A023I8X8,Cytochrome c oxidase subunit 1 (EC 7.1.1.9),cytochrome-c oxidase activity [GO:0004129]; he...,oxidative phosphorylation [GO:0006119]
4,COX1,A0A023I9A1,Cytochrome c oxidase subunit 1 (EC 7.1.1.9),cytochrome-c oxidase activity [GO:0004129]; he...,oxidative phosphorylation [GO:0006119]
...,...,...,...,...,...
1510,MAOA,Q5ULA9,Monoamine oxidase A,oxidoreductase activity [GO:0016491],NaN
1511,MAOB,P27338,Amine oxidase [flavin-containing] B (EC 1.4.3....,electron transfer activity [GO:0009055]; flavi...,dopamine catabolic process [GO:0042420]; hydro...
1512,MAOB,Q8TBI1,Amine oxidase (EC 1.4.3.-),monoamine oxidase activity [GO:0097621]; prima...,dopamine catabolic process [GO:0042420]
1513,AT1,O00400,Acetyl-coenzyme A transporter 1 (AT-1) (Acetyl...,acetyl-CoA transmembrane transporter activity ...,acetyl-CoA transmembrane transport [GO:0035348...
1514,AT1,Q13063,Type 1 angiotensin II receptor isoform,NaN,NaN

In [4]:
file2 = pd.read_csv(file2, sep="\t", header=0)
file2

,From,Entry,Protein names,Gene Ontology (molecular function),Gene Ontology (biological process),Gene Names
0,P43220,P43220,Glucagon-like peptide 1 receptor (GLP-1 recept...,glucagon receptor activity [GO:0004967]; gluca...,activation of adenylate cyclase activity [GO:0...,GLP1R
1,P48546,P48546,Gastric inhibitory polypeptide receptor (GIP-R...,G protein-coupled peptide receptor activity [G...,activation of adenylate cyclase activity [GO:0...,GIPR
2,Q86Z14,Q86Z14,Beta-klotho (BKL) (BetaKlotho) (Klotho beta-li...,fibroblast growth factor binding [GO:0017134];...,carbohydrate metabolic process [GO:0005975]; p...,KLB
3,P11362,P11362,Fibroblast growth factor receptor 1 (FGFR-1) (...,ATP binding [GO:0005524]; fibroblast growth fa...,angiogenesis [GO:0001525]; auditory receptor c...,FGFR1 BFGFR CEK FGFBR FLG FLT2 HBGFR
4,Q8NBP7,Q8NBP7,Proprotein convertase subtilisin/kexin type 9 ...,apolipoprotein binding [GO:0034185]; apolipopr...,apoptotic process [GO:0006915]; cellular respo...,PCSK9 NARC1 PSEC0052
5,Q96P20,Q96P20,"NACHT, LRR and PYD domains-containing protein ...",ADP binding [GO:0043531]; ATP binding [GO:0005...,apoptotic process [GO:0006915]; cellular respo...,NLRP3 C1orf7 CIAS1 NALP3 PYPAF1

In [5]:
df3 = pd.read_csv(file_nfkb, sep="\t", header=0)
df3

,Entry,Protein names,Gene Ontology (molecular function),Gene Ontology (biological process),Gene Names
0,O00221,NF-kappa-B inhibitor epsilon (NF-kappa-BIE) (I...,protein sequestering activity [GO:0140311],NaN,NFKBIE IKBE
1,O00255,Menin,chromatin binding [GO:0003682]; double-strande...,DNA damage response [GO:0006974]; DNA repair [...,MEN1 SCG2
2,O00571,ATP-dependent RNA helicase DDX3X (EC 3.6.4.13)...,ATP binding [GO:0005524]; ATP hydrolysis activ...,cell differentiation [GO:0030154]; cellular re...,DDX3X DBX DDX3
3,O14920,Inhibitor of nuclear factor kappa-B kinase sub...,ATP binding [GO:0005524]; identical protein bi...,antigen processing and presentation of exogeno...,IKBKB IKKB
4,O15111,Inhibitor of nuclear factor kappa-B kinase sub...,ATP binding [GO:0005524]; IkappaB kinase activ...,anatomical structure morphogenesis [GO:0009653...,CHUK IKKA TCF16
...,...,...,...,...,...
146,Q5T0Y2,MDM4 regulator of p53,zinc ion binding [GO:0008270],negative regulation of apoptotic process [GO:0...,MDM4
147,Q6ZNS7,"cDNA FLJ27229 fis, clone SYN05701",NaN,NaN,NaN
148,Q7Z430,Putative NFkB activating protein (Wnt ligand s...,Wnt-protein binding [GO:0017147],Wnt signaling pathway [GO:0016055],WLS
149,Q8N2N3,"cDNA FLJ90102 fis, clone HEMBA1006299, highly ...",Wnt-protein binding [GO:0017147],Wnt signaling pathway [GO:0016055],NaN
150,Q96F54,RELA protein,DNA binding [GO:0003677]; DNA-binding transcri...,NaN,RELA

In [6]:
# Select rows that contain "NFKB" in the "Gene Names" column
df_nfkb = df3[df3["Gene Names"].str.contains("NFKB", case=False, na=False)]
df_nfkb["From"] = "NFKB"

/tmp/ipykernel_1072615/3149113114.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nfkb["From"] = "NFKB"

In [7]:
# Concatenate the three dataframes - keep only From Entry	Protein names	Gene Ontology (molecular function)	Gene Ontology (biological process)
df_combined = pd.concat([df1[["From", "Entry", "Protein names", "Gene Ontology (molecular function)", "Gene Ontology (biological process)"]],
                         file2[["From", "Entry", "Protein names", "Gene Ontology (molecular function)", "Gene Ontology (biological process)"]],
                         df_nfkb[["From", "Entry", "Protein names", "Gene Ontology (molecular function)", "Gene Ontology (biological process)"]]])
df_combined

,From,Entry,Protein names,Gene Ontology (molecular function),Gene Ontology (biological process)
0,COX1,P23219,Prostaglandin G/H synthase 1 (EC 1.14.99.1) (C...,heme binding [GO:0020037]; metal ion binding [...,cyclooxygenase pathway [GO:0019371]; long-chai...
1,COX1,A0A023I8C2,Cytochrome c oxidase subunit 1 (EC 7.1.1.9),cytochrome-c oxidase activity [GO:0004129]; he...,oxidative phosphorylation [GO:0006119]
2,COX1,A0A023I8E0,Cytochrome c oxidase subunit 1 (EC 7.1.1.9),cytochrome-c oxidase activity [GO:0004129]; he...,oxidative phosphorylation [GO:0006119]
3,COX1,A0A023I8X8,Cytochrome c oxidase subunit 1 (EC 7.1.1.9),cytochrome-c oxidase activity [GO:0004129]; he...,oxidative phosphorylation [GO:0006119]
4,COX1,A0A023I9A1,Cytochrome c oxidase subunit 1 (EC 7.1.1.9),cytochrome-c oxidase activity [GO:0004129]; he...,oxidative phosphorylation [GO:0006119]
...,...,...,...,...,...
133,NFKB,H3BNC2,NFKB inhibitor epsilon,NaN,NaN
137,NFKB,H7C5S1,NFKB inhibitor zeta,NaN,NaN
138,NFKB,I3L1A4,NFKB inhibitor beta,NaN,NaN
139,NFKB,I3L4X3,NFKB inhibitor beta,NaN,NaN
142,NFKB,K7ENW9,NFKB inhibitor delta,NaN,NaN

In [8]:
hum_degree_file = "./data/human_protein_degrees.csv"
hum_degree = pd.read_csv(hum_degree_file)
hum_degree = hum_degree.set_index("protein")
hum_degree

         degree_human
protein
O60487         832447
O60658         857726
O75208         875597
P09327         666721
P22223         829871
...               ...
Q99962         846628
Q9BV68         876703
Q9C075         191172
Q9HBH0         862714
Q9ULH0         861578

[9782 rows x 1 columns]

In [9]:
# Merge the chemical experiment data with the human protein degree data
merged_df = df_combined.merge(hum_degree, left_on="Entry", right_index=True, how="left")
merged_df = merged_df.dropna(subset=["degree_human"])

# Rename columns for clarity
merged_df = merged_df.rename(columns={"From": "Gene", "Entry": "Protein", "degree_human": "Degree"})
merged_df = merged_df.reset_index(drop=True)
merged_df = merged_df.reset_index(drop=True)
merged_df

,Gene,Protein,Protein names,Gene Ontology (molecular function),Gene Ontology (biological process),Degree
0,COX1,P23219,Prostaglandin G/H synthase 1 (EC 1.14.99.1) (C...,heme binding [GO:0020037]; metal ion binding [...,cyclooxygenase pathway [GO:0019371]; long-chai...,747956.0
1,COX2,P00403,Cytochrome c oxidase subunit 2 (EC 7.1.1.9) (C...,copper ion binding [GO:0005507]; cytochrome-c ...,ATP synthesis coupled electron transport [GO:0...,836785.0
2,COX2,P35354,Prostaglandin G/H synthase 2 (EC 1.14.99.1) (C...,enzyme binding [GO:0019899]; heme binding [GO:...,brown fat cell differentiation [GO:0050873]; c...,767698.0
3,MAOA,P21397,Amine oxidase [flavin-containing] A (EC 1.4.3....,flavin adenine dinucleotide binding [GO:005066...,biogenic amine metabolic process [GO:0006576];...,878739.0
4,MAOB,P27338,Amine oxidase [flavin-containing] B (EC 1.4.3....,electron transfer activity [GO:0009055]; flavi...,dopamine catabolic process [GO:0042420]; hydro...,881829.0
5,P11362,P11362,Fibroblast growth factor receptor 1 (FGFR-1) (...,ATP binding [GO:0005524]; fibroblast growth fa...,angiogenesis [GO:0001525]; auditory receptor c...,854918.0
6,NFKB,O00221,NF-kappa-B inhibitor epsilon (NF-kappa-BIE) (I...,protein sequestering activity [GO:0140311],NaN,883934.0
7,NFKB,P19838,Nuclear factor NF-kappa-B p105 subunit (DNA-bi...,actinin binding [GO:0042805]; chromatin bindin...,antibacterial innate immune response [GO:01403...,879996.0
8,NFKB,P25963,NF-kappa-B inhibitor alpha (I-kappa-B-alpha) (...,enzyme binding [GO:0019899]; identical protein...,B cell receptor signaling pathway [GO:0050853]...,854401.0
9,NFKB,Q00653,Nuclear factor NF-kappa-B p100 subunit (DNA-bi...,"DNA-binding transcription activator activity, ...",canonical NF-kappaB signal transduction [GO:00...,865487.0
10,NFKB,Q04206,Transcription factor p65 (Nuclear factor NF-ka...,actinin binding [GO:0042805]; ankyrin repeat b...,animal organ morphogenesis [GO:0009887]; antiv...,861194.0

In [10]:
# For each human protein in the merged dataframe, read the parquet file with its interactions under notebooks/GUT_MB_Clinical/data/inference_results/per_protein_results and obtain a random bacterial interactor as an example.
# Add it as extra columns to the merged dataframe and save it as a new dataframe.
interactor_list = []
for protein in merged_df["Protein"]:
    parquet_file = f"./data/inference_results/per_protein_results/{protein}_predictions.parquet"
    interactions_df = pd.read_parquet(parquet_file)
    if not interactions_df.empty:
        random_interactor = interactions_df.sample(n=1)
        interactor_list.append(random_interactor["bacterial_protein"].values[0])
    else:
        interactor_list.append(None)
merged_df["Random_Bacterial_Interactor"] = interactor_list
merged_df.to_csv("./data/merged_chem_exp_human_degree.csv", index=False)